MERGE INTO PUBLIC.PRODUCT
(PRODUCT_ID,CATEGORY, NAME, PRICE)
VALUES(1,'COFFEE', 'American coffee', 5)
;
MERGE INTO PUBLIC.PRODUCT
(PRODUCT_ID,CATEGORY, NAME, PRICE)
VALUES(2,'COFFEE', 'Colombian coffee', 6)
;
MERGE INTO PUBLIC.PRODUCT
(PRODUCT_ID,CATEGORY, NAME, PRICE)
VALUES(3,'COFFEE', 'Coffee express', 3)
;

MERGE INTO PUBLIC.PRODUCT
(PRODUCT_ID,CATEGORY, NAME, PRICE)
VALUES(4,'EQUIPMENT', 'Car', 500)
;
MERGE INTO PUBLIC.PRODUCT
(PRODUCT_ID,CATEGORY, NAME, PRICE)
VALUES(5,'EQUIPMENT', 'Motorcycle', 50)
;
MERGE INTO PUBLIC.PRODUCT
(PRODUCT_ID,CATEGORY, NAME, PRICE)
VALUES(6,'EQUIPMENT', 'Bike', 20)
;

MERGE INTO PUBLIC.PRODUCT
(PRODUCT_ID,CATEGORY, NAME, PRICE)
VALUES(7,'ACCESSORIES', 'Earring', 20)
;
MERGE INTO PUBLIC.PRODUCT
(PRODUCT_ID,CATEGORY, NAME, PRICE)
VALUES(8,'ACCESSORIES', 'Ring', 30)
;
MERGE INTO PUBLIC.PRODUCT
(PRODUCT_ID,CATEGORY, NAME, PRICE)
VALUES(9,'ACCESSORIES', 'Bracelet', 45)
;